#Import necessary libraries
library(data.table)
library(dpylr)

#import master pheno file and subset by pop
master_phenos <- read.table("/home/ashley/LCL_chemotherapy/master_cytotoxicity_info_130311_plus_igrowth.txt", header = T)
YRI_phenos <- subset(master_phenos, pop == "YRI")
CEU_phenos <- subset(master_phenos, pop == "CEU")
CHB_phenos <- subset(master_phenos, pop == "CHB")
JPT_phenos <- subset(master_phenos, pop == "JPT")
ASN_phenos <- full_join(JPT_phenos, CHB_phenos)

#import fam file for each pop and set column names
YRI_fam <- fread("/home/ashley/LCL_chemotherapy/YRI/YRI.chr10.TGP_and_imputed.20130416.exclude_BAD_SNPs.fam")
CEU_fam <- fread("/home/ashley/LCL_chemotherapy/CEU/CEU.chr10.TGP_and_imputed.20130416.exclude_BAD_SNPs.fam")
ASN_fam <- fread("/home/ashley/LCL_chemotherapy/ASN/ASN.chr10.TGP_and_imputed.20130718.phased.R2gt0.8.fam")
colnames(YRI_fam) <- c("FID", "IID", "FatID", "MatID", "Sex", "Pheno")
colnames(CEU_fam) <- c("FID", "IID", "FatID", "MatID", "Sex", "Pheno")
colnames(ASN_fam) <- c("FID", "IID", "FatID", "MatID", "Sex", "Pheno")

#join pheno with with fam, keeping row order consistent with that of fam
YRI_phenos_ordered <- left_join(YRI_fam, YRI_phenos, by = c("FID" = "FID", "IID" = "IID"))
CEU_phenos_ordered <- left_join(CEU_fam, CEU_phenos, by = c("FID" = "FID", "IID" = "IID"))
ASN_phenos_ordered <- left_join(ASN_fam, ASN_phenos, by = c("FID" = "FID", "IID" = "IID"))

YRI_phenos_ordered<-select(YRI_phenos_ordered, 1:2, 7:46)
CEU_phenos_ordered<-select(CEU_phenos_ordered, 1:2, 7:46)
ASN_phenos_ordered<-select(ASN_phenos_ordered, 1:2, 7:46)

#Create pheno data frames for reference (with ids)
YRI_carbo_pheno_ids<-select(YRI_phenos_ordered, 1:12, contains("CARBO_RnIC50"))
CEU_carbo_pheno_ids<-select(CEU_phenos_ordered, 1:12, contains("CARBO_RnIC50"))
ASN_carbo_pheno_ids<-select(ASN_phenos_ordered, 1:12, contains("CARBO_RnIC50"))
YRI_arac_pheno_ids<-select(YRI_phenos_ordered, 1:12, contains("ARAC_RnAUC"))
CEU_arac_pheno_ids<-select(CEU_phenos_ordered, 1:12, contains("ARAC_RnAUC"))
ASN_arac_pheno_ids<-select(ASN_phenos_ordered, 1:12, contains("ARAC_RnAUC"))
YRI_cis_pheno_ids<-select(YRI_phenos_ordered, 1:12, contains("CIS_RnIC50"))
CEU_cis_pheno_ids<-select(CEU_phenos_ordered, 1:12, contains("CIS_RnIC50"))
ASN_cis_pheno_ids<-select(ASN_phenos_ordered, 1:12, contains("CIS_RnIC50"))
YRI_cape_pheno_ids<-select(YRI_phenos_ordered, 1:12, contains("CAPE_RnAUC"))
CEU_cape_pheno_ids<-select(CEU_phenos_ordered, 1:12, contains("CAPE_RnAUC"))
ASN_cape_pheno_ids<-select(ASN_phenos_ordered, 1:12, contains("CAPE_RnAUC"))
YRI_etop_pheno_ids<-select(YRI_phenos_ordered, 1:12, contains("ETOP_Rn_IC50"))
CEU_etop_pheno_ids<-select(CEU_phenos_ordered, 1:12, contains("ETOP_Rn_IC50"))
YRI_pacl_pheno_ids<-select(YRI_phenos_ordered, 1:12, contains("PACL_Rn_AUC"))
CEU_pacl_pheno_ids<-select(CEU_phenos_ordered, 1:12, contains("PACL_Rn_AUC"))
YRI_dauno_pheno_ids<-select(YRI_phenos_ordered, 1:12, contains("DAUNO_RnIC50"))
CEU_dauno_pheno_ids<-select(CEU_phenos_ordered, 1:12, contains("DAUNO_RnIC50"))
YRI_peme_pheno_ids<-select(YRI_phenos_ordered, 1:12, contains("PEME_RnAUC"))
CEU_peme_pheno_ids<-select(CEU_phenos_ordered, 1:12, contains("PEME_RnAUC"))

#Create pheno data frames for use (without ids)
YRI_carbo_pheno_noids<-select(YRI_phenos_ordered, contains("CARBO_RnIC50"))
CEU_carbo_pheno_noids<-select(CEU_phenos_ordered, contains("CARBO_RnIC50"))
ASN_carbo_pheno_noids<-select(ASN_phenos_ordered, contains("CARBO_RnIC50"))
YRI_arac_pheno_noids<-select(YRI_phenos_ordered, contains("ARAC_RnAUC"))
CEU_arac_pheno_noids<-select(CEU_phenos_ordered, contains("ARAC_RnAUC"))
ASN_arac_pheno_noids<-select(ASN_phenos_ordered, contains("ARAC_RnAUC"))
YRI_cis_pheno_noids<-select(YRI_phenos_ordered, contains("CIS_RnIC50"))
CEU_cis_pheno_noids<-select(CEU_phenos_ordered, contains("CIS_RnIC50"))
ASN_cis_pheno_noids<-select(ASN_phenos_ordered, contains("CIS_RnIC50"))
YRI_cape_pheno_noids<-select(YRI_phenos_ordered, contains("CAPE_RnAUC"))
CEU_cape_pheno_noids<-select(CEU_phenos_ordered, contains("CAPE_RnAUC"))
ASN_cape_pheno_noids<-select(ASN_phenos_ordered, contains("CAPE_RnAUC"))
YRI_etop_pheno_noids<-select(YRI_phenos_ordered, contains("ETOP_Rn_IC50"))
CEU_etop_pheno_noids<-select(CEU_phenos_ordered, contains("ETOP_Rn_IC50"))
YRI_pacl_pheno_noids<-select(YRI_phenos_ordered, contains("PACL_Rn_AUC"))
CEU_pacl_pheno_noids<-select(CEU_phenos_ordered, contains("PACL_Rn_AUC"))
YRI_dauno_pheno_noids<-select(YRI_phenos_ordered, contains("DAUNO_RnIC50"))
CEU_dauno_pheno_noids<-select(CEU_phenos_ordered, contains("DAUNO_RnIC50"))
YRI_peme_pheno_noids<-select(YRI_phenos_ordered, contains("PEME_RnAUC"))
CEU_peme_pheno_noids<-select(CEU_phenos_ordered, contains("PEME_RnAUC"))

#Output pheno data frames for reference
write.table(YRI_arac_pheno_ids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_arac_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_arac_pheno_ids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_arac_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(ASN_arac_pheno_ids, "/home/ashley/LCL_chemotherapy/ASN/ASN_phenotypes/ASN_arac_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(YRI_cape_pheno_ids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_cape_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_cape_pheno_ids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_cape_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(ASN_cape_pheno_ids, "/home/ashley/LCL_chemotherapy/ASN/ASN_phenotypes/ASN_cape_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(YRI_carbo_pheno_ids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_carbo_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_carbo_pheno_ids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_carbo_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(ASN_carbo_pheno_ids, "/home/ashley/LCL_chemotherapy/ASN/ASN_phenotypes/ASN_carbo_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(YRI_dauno_pheno_ids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_dauno_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_dauno_pheno_ids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_dauno_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(YRI_etop_pheno_ids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_etop_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_etop_pheno_ids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_etop_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(YRI_pacl_pheno_ids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_pacl_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_pacl_pheno_ids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_pacl_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(YRI_cis_pheno_ids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_cis_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_cis_pheno_ids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_cis_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(ASN_cis_pheno_ids, "/home/ashley/LCL_chemotherapy/ASN/ASN_phenotypes/ASN_cis_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(YRI_peme_pheno_ids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_peme_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_peme_pheno_ids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_peme_bestpheno_ids.txt", col.names = F, row.names = F, sep = "\t", quote = F)

#Output pheno data frames for use
write.table(YRI_arac_pheno_noids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_arac_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_arac_pheno_noids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_arac_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(ASN_arac_pheno_noids, "/home/ashley/LCL_chemotherapy/ASN/ASN_phenotypes/ASN_arac_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(YRI_cape_pheno_noids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_cape_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_cape_pheno_noids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_cape_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(ASN_cape_pheno_noids, "/home/ashley/LCL_chemotherapy/ASN/ASN_phenotypes/ASN_cape_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(YRI_carbo_pheno_noids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_carbo_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_carbo_pheno_noids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_carbo_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(ASN_carbo_pheno_noids, "/home/ashley/LCL_chemotherapy/ASN/ASN_phenotypes/ASN_carbo_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(YRI_dauno_pheno_noids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_dauno_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_dauno_pheno_noids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_dauno_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(YRI_etop_pheno_noids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_etop_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_etop_pheno_noids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_etop_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(YRI_pacl_pheno_noids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_pacl_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_pacl_pheno_noids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_pacl_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(YRI_cis_pheno_noids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_cis_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_cis_pheno_noids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_cis_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(ASN_cis_pheno_noids, "/home/ashley/LCL_chemotherapy/ASN/ASN_phenotypes/ASN_cis_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(YRI_peme_pheno_noids, "/home/ashley/LCL_chemotherapy/YRI/YRI_phenotypes/YRI_peme_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
write.table(CEU_peme_pheno_noids, "/home/ashley/LCL_chemotherapy/CEU/CEU_phenotypes/CEU_peme_bestpheno_noids.txt", col.names = F, row.names = F, sep = "\t", quote = F)
