#Import necessary libraries
library(data.table)
library(dplyr)

#Read in master pheno file and subset by pop
master_phenos <- read.table("/home/ashley/LCL_chemotherapy/master_cytotoxicity_info_130311_plus_igrowth.txt", header = T)
YRI_phenos <- subset(master_phenos, pop == "YRI")
CEU_phenos <- subset(master_phenos, pop == "CEU")
CHB_phenos <- subset(master_phenos, pop == "CHB")
JPT_phenos <- subset(master_phenos, pop == "JPT")
ASN_phenos <- full_join(JPT_phenos, CHB_phenos)

#Read in fam file for each pop and set column names
YRI_fam <- fread("/home/ashley/LCL_chemotherapy/YRI/YRI.chr10.TGP_and_imputed.20130416.exclude_BAD_SNPs.fam")
CEU_fam <- fread("/home/ashley/LCL_chemotherapy/CEU/CEU.chr10.TGP_and_imputed.20130416.exclude_BAD_SNPs.fam")
ASN_fam <- fread("/home/ashley/LCL_chemotherapy/ASN/ASN.chr10.TGP_and_imputed.20130718.phased.R2gt0.8.fam")
colnames(YRI_fam) <- c("FID", "IID", "FatID", "MatID", "Sex", "Pheno")
colnames(CEU_fam) <- c("FID", "IID", "FatID", "MatID", "Sex", "Pheno")
colnames(ASN_fam) <- c("FID", "IID", "FatID", "MatID", "Sex", "Pheno")

#Join pheno with with fam, keeping row order consistent with that of fam
YRI_phenos_ordered <- left_join(YRI_fam, YRI_phenos, by = c("FID" = "FID", "IID" = "IID"))
CEU_phenos_ordered <- left_join(CEU_fam, CEU_phenos, by = c("FID" = "FID", "IID" = "IID"))
ASN_phenos_ordered <- left_join(ASN_fam, ASN_phenos, by = c("FID" = "FID", "IID" = "IID"))

#Create three-column pheno data frames, with column names FID, IID, and Pheno
YRI_carbo_pheno<-select(YRI_phenos_ordered, 1:2, contains("CARBO_RnIC50"))
colnames(YRI_carbo_pheno) <- c("FID", "IID", "Pheno")
CEU_carbo_pheno<-select(CEU_phenos_ordered, 1:2, contains("CARBO_RnIC50"))
colnames(CEU_carbo_pheno) <- c("FID", "IID", "Pheno")
ASN_carbo_pheno<-select(ASN_phenos_ordered, 1:2, contains("CARBO_RnIC50"))
colnames(ASN_carbo_pheno) <- c("FID", "IID", "Pheno")
YRI_arac_pheno<-select(YRI_phenos_ordered, 1:2, contains("ARAC_RnAUC"))
colnames(YRI_arac_pheno) <- c("FID", "IID", "Pheno")
CEU_arac_pheno<-select(CEU_phenos_ordered, 1:2, contains("ARAC_RnAUC"))
colnames(CEU_arac_pheno) <- c("FID", "IID", "Pheno")
ASN_arac_pheno<-select(ASN_phenos_ordered, 1:2, contains("ARAC_RnAUC"))
colnames(ASN_arac_pheno) <- c("FID", "IID", "Pheno")
YRI_cis_pheno<-select(YRI_phenos_ordered, 1:2, contains("CIS_RnIC50"))
colnames(YRI_cis_pheno) <- c("FID", "IID", "Pheno")
CEU_cis_pheno<-select(CEU_phenos_ordered, 1:2, contains("CIS_RnIC50"))
colnames(CEU_cis_pheno) <- c("FID", "IID", "Pheno")
ASN_cis_pheno<-select(ASN_phenos_ordered, 1:2, contains("CIS_RnIC50"))
colnames(ASN_cis_pheno) <- c("FID", "IID", "Pheno")
YRI_cape_pheno<-select(YRI_phenos_ordered, 1:2, contains("CAPE_RnAUC"))
colnames(YRI_cape_pheno) <- c("FID", "IID", "Pheno")
CEU_cape_pheno<-select(CEU_phenos_ordered, 1:2, contains("CAPE_RnAUC"))
colnames(CEU_cape_pheno) <- c("FID", "IID", "Pheno")
ASN_cape_pheno<-select(ASN_phenos_ordered, 1:2, contains("CAPE_RnAUC"))
colnames(ASN_cape_pheno) <- c("FID", "IID", "Pheno")
YRI_etop_pheno<-select(YRI_phenos_ordered, 1:2, contains("ETOP_Rn_IC50"))
colnames(YRI_etop_pheno) <- c("FID", "IID", "Pheno")
CEU_etop_pheno<-select(CEU_phenos_ordered, 1:2, contains("ETOP_Rn_IC50"))
colnames(CEU_etop_pheno) <- c("FID", "IID", "Pheno")
YRI_pacl_pheno<-select(YRI_phenos_ordered, 1:2, contains("PACL_Rn_AUC"))
colnames(YRI_pacl_pheno) <- c("FID", "IID", "Pheno")
CEU_pacl_pheno<-select(CEU_phenos_ordered, 1:2, contains("PACL_Rn_AUC"))
colnames(CEU_pacl_pheno) <- c("FID", "IID", "Pheno")
YRI_dauno_pheno<-select(YRI_phenos_ordered, 1:2, contains("DAUNO_RnIC50"))
colnames(YRI_dauno_pheno) <- c("FID", "IID", "Pheno")
CEU_dauno_pheno<-select(CEU_phenos_ordered, 1:2, contains("DAUNO_RnIC50"))
colnames(CEU_dauno_pheno) <- c("FID", "IID", "Pheno")
YRI_peme_pheno<-select(YRI_phenos_ordered, 1:2, contains("PEME_RnAUC"))
colnames(YRI_peme_pheno) <- c("FID", "IID", "Pheno")
CEU_peme_pheno<-select(CEU_phenos_ordered, 1:2, contains("PEME_RnAUC"))
colnames(CEU_peme_pheno) <- c("FID", "IID", "Pheno")

#Output pheno data frames
write.table(YRI_arac_pheno, "/home/ashley/LCL_chemotherapy/YRI/YRI_arac_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(CEU_arac_pheno, "/home/ashley/LCL_chemotherapy/CEU/CEU_arac_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(ASN_arac_pheno, "/home/ashley/LCL_chemotherapy/ASN/ASN_arac_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(YRI_cape_pheno, "/home/ashley/LCL_chemotherapy/YRI/YRI_cape_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(CEU_cape_pheno, "/home/ashley/LCL_chemotherapy/CEU/CEU_cape_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(ASN_cape_pheno, "/home/ashley/LCL_chemotherapy/ASN/ASN_cape_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(YRI_carbo_pheno, "/home/ashley/LCL_chemotherapy/YRI/YRI_carbo_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(CEU_carbo_pheno, "/home/ashley/LCL_chemotherapy/CEU/CEU_carbo_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(ASN_carbo_pheno, "/home/ashley/LCL_chemotherapy/ASN/ASN_carbo_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(YRI_dauno_pheno, "/home/ashley/LCL_chemotherapy/YRI/YRI_dauno_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(CEU_dauno_pheno, "/home/ashley/LCL_chemotherapy/CEU/CEU_dauno_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(YRI_etop_pheno, "/home/ashley/LCL_chemotherapy/YRI/YRI_etop_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(CEU_etop_pheno, "/home/ashley/LCL_chemotherapy/CEU/CEU_etop_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(YRI_pacl_pheno, "/home/ashley/LCL_chemotherapy/YRI/YRI_pacl_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(CEU_pacl_pheno, "/home/ashley/LCL_chemotherapy/CEU/CEU_pacl_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(YRI_cis_pheno, "/home/ashley/LCL_chemotherapy/YRI/YRI_cis_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(CEU_cis_pheno, "/home/ashley/LCL_chemotherapy/CEU/CEU_cis_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(ASN_cis_pheno, "/home/ashley/LCL_chemotherapy/ASN/ASN_cis_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(YRI_peme_pheno, "/home/ashley/LCL_chemotherapy/YRI/YRI_peme_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
write.table(CEU_peme_pheno, "/home/ashley/LCL_chemotherapy/CEU/CEU_peme_pheno.txt", col.names = T, row.names = F, sep = "\t", quote = F)
